# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Linux-BootCleanup
version:      0.02
version_from: lib/Linux/BootCleanup.pm
installdirs:  site
requires:
    Archive::Tar:                  0
    Exporter:                      0
    Getopt::ArgvFile:              0
    Getopt::Long:                  0
    IO::Prompt:                    0
    Linux::Bootloader:             0
    Linux::Bootloader::Detect:     0
    Pod::Usage:                    0
    POSIX:                         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
